
inherit_from: ../.rubocop.yml

# Lengthen for long descriptions.
LineLength:
  Max: 120

# raise_error matcher always requires {} form block.
Blocks:
  Enabled: false

# Sometimes block alignment does not suit RSpec syntax.
BlockAlignment:
  Enabled: false

# Suppress offences for namespace classes only with #describe.
ClassLength:
  Enabled: false
